In [ ]:
import os
from dotenv import load_dotenv
from utils import extract, transform, load

load_dotenv()
access_key = os.getenv('ACCESS_KEY')

# Define API endpoint
url = 'https://www.goflightlabs.com/flights'

# Extracting data from API endpoint
flight_data_raw = extract(url, access_key)
print(flight_data_raw.shape)

Returned status code: 200
Extraction complete
(100, 22)

In [ ]:
# EDA
display(flight_data_raw.head(), flight_data_raw.info(), flight_data_raw.describe())

print('\nNumber of null values for every column feature\n')
flight_data_raw.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   hex            100 non-null    object
 1   reg_number     100 non-null    object
 2   flag           100 non-null    object
 3   lat            100 non-null    float64
 4   lng            100 non-null    float64
 5   alt            100 non-null    int64
 6   dir            100 non-null    float64
 7   speed          100 non-null    int64
 8   v_speed        100 non-null    int64
 9   flight_number  100 non-null    object
 10  flight_icao    100 non-null    object
 11  flight_iata    100 non-null    object
 12  dep_icao       100 non-null    object
 13  dep_iata       100 non-null    object
 14  arr_icao       100 non-null    object
 15  arr_iata       100 non-null    object
 16  airline_icao   100 non-null    object
 17  airline_iata   100 non-null    object
 18  aircraft_icao  100 non-null    object
 19  updated        100 non-null    int64
 20  status         100 non-null    object
 21  type           100 non-null    object
dtypes: float64(3), int64(4), object(15)
memory usage: 17.3+ KB

,hex,reg_number,flag,lat,lng,alt,dir,speed,v_speed,flight_number,...,dep_icao,dep_iata,arr_icao,arr_iata,airline_icao,airline_iata,aircraft_icao,updated,status,type
0,0D0ABF,XA-VRD,MX,31.509855,-116.425550,6938,349.8,745,0,3235,...,MMLP,LAP,MMTJ,TIJ,VOI,Y4,A20N,1764720909,en-route,adsb
1,7C47A6,VH-OFS,AU,-37.726550,144.851957,391,319.6,251,0,31,...,YMML,MEL,WADD,DPS,JST,JQ,A21N,1764720909,en-route,adsb
2,E48DC1,PR-MYY,CL,-29.747184,-51.280172,2288,216.8,498,0,3162,...,SBSP,CGH,SBPA,POA,TAM,JJ,A320,1764720909,en-route,adsb
3,A1272F,N17333,US,40.366732,-123.184586,10299,179.9,970,0,1230,...,CYVR,YVR,KSFO,SFO,UAL,UA,B38M,1764720909,en-route,adsb
4,AACFE9,N796SK,US,47.089478,-103.842917,6847,4.0,745,0,5463,...,KDEN,DEN,KXWA,XWA,SKW,OO,CRJ7,1764720909,en-route,adsb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,A3C2A9,N341SV,US,20.221142,-78.370223,10688,168.8,861,0,2197,...,KMIA,MIA,SKCL,CLO,AAL,AA,B38M,1764720909,en-route,adsb
96,ADE9C0,N996JL,US,21.998312,-69.935363,11259,122.5,872,0,1033,...,KMCO,MCO,TJSJ,SJU,JBU,B6,A321,1764720909,en-route,adsb
97,0D0DA4,XA-VSG,MX,19.723949,-101.768255,10649,290.7,773,0,1301,...,MMVA,VSA,MMGL,GDL,VOI,Y4,A20N,1764720909,en-route,adsb
98,0D0ECF,XA-VXH,MX,25.834440,-100.207134,977,121.7,367,0,4185,...,MMLO,BJX,MMMY,MTY,VIV,VB,A21N,1764720909,en-route,adsb
99,0D0BFF,XA-CCC,MX,25.196912,-100.034674,12143,174.7,795,0,659,...,KDEN,DEN,MMMX,MEX,AMX,AM,B38M,1764720909,en-route,adsb

None

,lat,lng,alt,dir,speed,v_speed,updated
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.0,1.000000e+02
mean,19.757835,1.011439,9221.980000,195.53100,773.400000,0.0,1.764721e+09
std,24.234086,101.299668,3045.707697,100.37444,169.513862,0.0,0.000000e+00
min,-37.726550,-159.448805,391.000000,4.00000,128.000000,0.0,1.764721e+09
25%,10.676321,-100.077789,7610.750000,111.70000,724.750000,0.0,1.764721e+09
50%,23.639840,-39.215988,10341.000000,216.90000,792.000000,0.0,1.764721e+09
75%,36.462311,109.143628,11341.250000,280.60000,869.500000,0.0,1.764721e+09
max,56.350074,153.089656,12653.000000,359.00000,1131.000000,0.0,1.764721e+09

Number of null values for every column feature

hex              0
reg_number       0
flag             0
lat              0
lng              0
alt              0
dir              0
speed            0
v_speed          0
flight_number    0
flight_icao      0
flight_iata      0
dep_icao         0
dep_iata         0
arr_icao         0
arr_iata         0
airline_icao     0
airline_iata     0
aircraft_icao    0
updated          0
status           0
type             0
dtype: int64

<h1>Data Cleaning</h1>

<li>Replacing missing values in "squawk" column with "unknown"</li>
<li>Replacing missing values in 'alt', 'speed' and v_speed to 0</li>
<li>Renaming columns</li>
<li>Converting "updated" values to datetime</li>

In [ ]:
flight_data_clean = transform(flight_data_raw)

display(flight_data_clean.head())

print('\nNumber of null values for every column feature\n')
flight_data_clean.isnull().sum()

transform complete

,hex,reg_number,flag,latitude,longitude,altitude_ft,dir,speed_mph,v_speed_mph,flight_number,...,departure_icao,departure_iata,arrival_icao,arrival_iata,airline_icao,airline_iata,aircraft_icao,updated,status,type
0,0D0ABF,XA-VRD,MX,31.509855,-116.425550,22762.46792,349.8,462.921395,0.0,3235,...,MMLP,LAP,MMTJ,TIJ,VOI,Y4,A20N,2025-12-02 19:15:09,en-route,adsb
1,7C47A6,VH-OFS,AU,-37.726550,144.851957,1282.80844,319.6,155.964121,0.0,31,...,YMML,MEL,WADD,DPS,JST,JQ,A21N,2025-12-02 19:15:09,en-route,adsb
2,E48DC1,PR-MYY,CL,-29.747184,-51.280172,7506.56192,216.8,309.442758,0.0,3162,...,SBSP,CGH,SBPA,POA,TAM,JJ,A320,2025-12-02 19:15:09,en-route,adsb
3,A1272F,N17333,US,40.366732,-123.184586,33789.37116,179.9,602.729870,0.0,1230,...,CYVR,YVR,KSFO,SFO,UAL,UA,B38M,2025-12-02 19:15:09,en-route,adsb
4,AACFE9,N796SK,US,47.089478,-103.842917,22463.91148,4.0,462.921395,0.0,5463,...,KDEN,DEN,KXWA,XWA,SKW,OO,CRJ7,2025-12-02 19:15:09,en-route,adsb

,hex,reg_number,flag,lat,lng,alt,dir,speed,v_speed,flight_number,...,dep_icao,dep_iata,arr_icao,arr_iata,airline_icao,airline_iata,aircraft_icao,updated,status,type
0,0D0ABF,XA-VRD,MX,31.509855,-116.425550,6938,349.8,745,0,3235,...,MMLP,LAP,MMTJ,TIJ,VOI,Y4,A20N,1764720909,en-route,adsb
1,7C47A6,VH-OFS,AU,-37.726550,144.851957,391,319.6,251,0,31,...,YMML,MEL,WADD,DPS,JST,JQ,A21N,1764720909,en-route,adsb
2,E48DC1,PR-MYY,CL,-29.747184,-51.280172,2288,216.8,498,0,3162,...,SBSP,CGH,SBPA,POA,TAM,JJ,A320,1764720909,en-route,adsb
3,A1272F,N17333,US,40.366732,-123.184586,10299,179.9,970,0,1230,...,CYVR,YVR,KSFO,SFO,UAL,UA,B38M,1764720909,en-route,adsb
4,AACFE9,N796SK,US,47.089478,-103.842917,6847,4.0,745,0,5463,...,KDEN,DEN,KXWA,XWA,SKW,OO,CRJ7,1764720909,en-route,adsb

Number of null values for every column feature

hex               0
reg_number        0
flag              0
latitude          0
longitude         0
altitude_ft       0
dir               0
speed_mph         0
v_speed_mph       0
flight_number     0
flight_icao       0
flight_iata       0
departure_icao    0
departure_iata    0
arrival_icao      0
arrival_iata      0
airline_icao      0
airline_iata      0
aircraft_icao     0
updated           0
status            0
type              0
dtype: int64